### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Donran**
Did a refactor of play() because it was not applying to the DRY rule. Changed small inconsistencies.

### CODE REVIEW

**Comment by andrewc2** [comment]
I promise I'm gonna get to this 😅

**Comment by Donran** [comment]
I think this is still borked

**Comment by andrewc2** [comment]
Oh dear you think so?

**Comment by andrewc2** [comment]
```events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: 4014: Disconnected.
    at WebSocket.<anonymous> (/home/redbot/node_modules/eris/lib/voice/VoiceConnection.js:341:57)
    at WebSocket.emit (events.js:210:5)
    at WebSocket.emitClose (/home/redbot/node_modules/eris/node_modules/ws/lib/websocket.js:193:10)
    at TLSSocket.socketOnClose (/home/redbot/node_modules/eris/node_modules/ws/lib/websocket.js:861:15)
    at TLSSocket.emit (events.js:215:7)
    at net.js:658:12
    at TCP.done (_tls_wrap.js:481:7)
Emitted 'error' event on VoiceConnection instance at:
    at VoiceConnection.disconnect (/home/redbot/node_modules/eris/lib/voice/VoiceConnection.js:394:22)
    at WebSocket.<anonymous> (/home/redbot/node_modules/eris/lib/voice/VoiceConnection.js:350:22)
    at WebSocket.emit (events.js:210:5)
    [... lines matching original stack trace ...]
    at TCP.done (_tls_wrap.js:481:7)
```

I guess it still doesn't handle voice disconnects well 😂

**Comment by andrewc2** [comment]
Some of this was merged, not currently implementing the DRY rule changes due to unexpected disconnects that do not occur in the non-DRY compliant code. As a result of the partial implementation I'll close the PR.

**Pull request closed without merging**
